### ISSUE TITLE
Revise content

### ISSUE THREAD

**Issue by dflynn-volpe** [VisionEval/VisionEval.org#2]
- Too much text on pages, break up with subheadings and graphics
- Should be able to guide new users to understand goals of VE, Pooled Fund, how they connect to existing models. New users should be able to navigate through the site and understand how to apply VE models. 

Completed:
 - Included case studies, in information for users
- Text has been changed to emphasize this is a collaborative project, hosted on GitHub, not a standalone, one-off project.

**Comment by jrawbits** [comment]
It feels like some progress has been made on this issue.  Please update it.

**Comment by dflynn-volpe** [comment]
Great -- I'm keeping this open, to keep track of revisions we'd still like to have, including more graphics.
